services:
  rabbitmq:
    image: rabbitmq:4.0.3-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/data
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 30s
      retries: 5

  postgres:
    build: .
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_MULTIPLE_DATABASES: notification

  notification-service:
    image: ghcr.io/thi-cnd/notification_service:latest
    volumes:
      - ./notification-service:/code
    ports:
      - "8081:8080"
      - "9091:9090"
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_URL: jdbc:postgresql://postgres:5432/notification
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBITMQ_EXCHANGE: recipemanagement
      RABBITMQ_ROUTING_KEYS_COLLECTION: collection.created,collection.updated,collection.deleted
      RABBITMQ_ROUTING_KEYS_REVIEW: review.created
      RABBITMQ_ROUTING_KEYS_USER: users.count
      RABBITMQ_QUEUE_COLLECTION: collection.queue
      RABBITMQ_QUEUE_REVIEW: review.queue
      RABBITMQ_QUEUE_USER: user.queue
      JAVA_TOOL_OPTIONS: "-XX:UseSVE=0" #Fix for ARM64 Bug
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy

volumes:
  postgres_data:
  rabbitmq_data: